import { DesignerElement } from '@/types/designer';

export const accessibilityAgent = {
    /**
     * Analyzes and fixes accessibility issues in a set of elements.
     * Returns a map of updates.
     */
    fixAccessibility: (elements: Record<string, DesignerElement>): Record<string, Partial<DesignerElement>> => {
        const updates: Record<string, Partial<DesignerElement>> = {};
        const elementList = Object.values(elements);

        elementList.forEach(el => {
            const update: Partial<DesignerElement> = {};
            let hasUpdate = false;

            // 1. Ensure Images have Alt Text
            if (el.type === 'image' && !el.altText) {
                update.altText = 'Descriptive image text generated by AI';
                hasUpdate = true;
            }

            // 2. Button contrast check (Mock logic)
            if (el.type === 'button') {
                const bg = el.styles?.backgroundColor as string;
                if (bg === '#ffffff' || bg === 'white') {
                    // If white bg, ensure dark text
                    if (el.styles?.color === '#ffffff' || el.styles?.color === 'white') {
                        update.styles = { ...el.styles, color: '#000000' };
                        hasUpdate = true;
                    }
                }
            }

            // 3. Form input labels
            if ((el.type === 'input' || el.type === 'textarea') && !el.props?.['aria-label']) {
                // If no label is associated (simplified check), add aria-label
                if (!el.props) update.props = {};
                update.props = { ...el.props, 'aria-label': el.name || 'Input Field' };
                hasUpdate = true;
            }

            // 4. Semantic Tags
            if (el.type === 'container' && el.name?.toLowerCase().includes('nav')) {
                update.tagName = 'nav';
                hasUpdate = true;
            }
            if (el.type === 'container' && el.name?.toLowerCase().includes('footer')) {
                update.tagName = 'footer';
                hasUpdate = true;
            }

            if (hasUpdate) {
                updates[el.id] = update;
            }
        });

        return updates;
    }
};
