
import { DesignerElement } from '@/types/designer';
import { v4 as uuidv4 } from 'uuid';
import { aiGateway } from './AIGateway';
import { ContextGatherer } from './ContextGatherer';

export class GenerativeCore {

    private static SYSTEM_PROMPT = `
You are the OMNIOS Design Engine. Your job is to generate UI component trees based on user requests.
Output strictly JSON.

Schema for a Node:
{
  "type": "section" | "container" | "text" | "button" | "image" | "input",
  "name": string,
  "content"?: string, // For text/button
  "styles": { ...CSS properties... },
  "children"?: Node[]
}

Rules:
1. Always start with a "section" or "container" root.
2. Use modern, clean, minimal design (Apple/Vercel aesthetic).
3. Use contrasting text colors (white on dark, black on light).
4. Do not include IDs, they will be generated by the system.
`;

    /**
     * Generates a layout using AI (or mock if no key).
     */
    static async generateLayout(prompt: string, contextState?: any): Promise<DesignerElement[]> {
        console.log(`[GenerativeCore] Analyzing prompt: "${prompt}"`);

        // Check availability
        try {
            const contextStr = contextState ? JSON.stringify(ContextGatherer.gatherContext(contextState)) : '';
            const fullPrompt = `User Request: "${prompt}"\n\nExisting Context: ${contextStr}`;

            const response = await aiGateway.generateJSON(fullPrompt, this.SYSTEM_PROMPT);

            if (response && response.data) {
                console.log("[GenerativeCore] real AI response received.");
                return this.transformAIOutputToElements(response.data);
            }
        } catch (e) {
            console.warn("[GenerativeCore] AI generation failed, falling back to templates.", e);
        }

        // FALLBACK MOCKS
        const lowerPrompt = prompt.toLowerCase();
        if (lowerPrompt.includes('hero') || lowerPrompt.includes('landing')) {
            return this.getHeroTemplate();
        }
        if (lowerPrompt.includes('feature') || lowerPrompt.includes('grid')) {
            return this.getFeatureGridTemplate();
        }
        return this.getDefaultTemplate(prompt);
    }

    /**
     * recursively transforms the AI's simplified tree into full DesignerElements with UUIDs.
     */
    private static transformAIOutputToElements(rootNode: any): DesignerElement[] {
        const flatList: DesignerElement[] = [];

        const maximize = (node: any, parentId: string | null) => {
            const id = uuidv4();
            const element: DesignerElement = {
                id,
                type: node.type || 'container',
                name: node.name || 'AI Generated',
                parentId,
                children: [], // filled later
                styles: node.styles || {},
                content: node.content
            };

            flatList.push(element);

            if (node.children && Array.isArray(node.children)) {
                node.children.forEach((child: any) => {
                    const childId = maximize(child, id);
                    element.children!.push(childId);
                });
            }
            return id;
        };

        maximize(rootNode, null);
        return flatList;
    }

    // --- LEGACY TEMPLATES RESCUED FOR FALLBACK ---

    private static getHeroTemplate(): DesignerElement[] {
        const sectionId = uuidv4();
        const containerId = uuidv4();
        const titleId = uuidv4();
        const subtitleId = uuidv4();
        const buttonId = uuidv4();

        return [
            {
                id: sectionId,
                type: 'section',
                name: 'AI Generated Hero',
                parentId: null,
                children: [containerId],
                styles: {
                    paddingTop: '120px',
                    paddingBottom: '120px',
                    backgroundColor: '#0A0A0A',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textAlign: 'center'
                }
            },
            {
                id: containerId,
                type: 'container',
                parentId: sectionId,
                children: [titleId, subtitleId, buttonId],
                styles: {
                    maxWidth: '800px',
                    width: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '24px'
                }
            },
            {
                id: titleId,
                type: 'text',
                parentId: containerId,
                content: 'Experience the Future of Design',
                styles: {
                    fontSize: '64px',
                    fontWeight: '800',
                    color: '#FFFFFF',
                    lineHeight: '1.1',
                    letterSpacing: '-0.04em'
                }
            },
            {
                id: subtitleId,
                type: 'text',
                parentId: containerId,
                content: 'Stop building. Start generating. The world\'s first autonomous design engine is here.',
                styles: {
                    fontSize: '20px',
                    color: '#A1A1AA',
                    lineHeight: '1.6'
                }
            },
            {
                id: buttonId,
                type: 'button',
                parentId: containerId,
                content: 'Get Started for Free',
                styles: {
                    paddingLeft: '32px',
                    paddingRight: '32px',
                    paddingTop: '16px',
                    paddingBottom: '16px',
                    backgroundColor: 'var(--accent-primary)',
                    color: '#000000',
                    borderRadius: '8px',
                    fontWeight: 'bold',
                    alignSelf: 'center',
                    marginTop: '12px',
                    boxShadow: '0 0 30px rgba(0, 224, 255, 0.4)'
                }
            }
        ];
    }

    private static getFeatureGridTemplate(): DesignerElement[] {
        const sectionId = uuidv4();
        const titleId = uuidv4();
        const gridId = uuidv4();

        const elements: DesignerElement[] = [
            {
                id: sectionId,
                type: 'section',
                name: 'AI Feature Section',
                parentId: null,
                children: [titleId, gridId],
                styles: {
                    padding: '80px 20px',
                    backgroundColor: '#111',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    gap: '48px'
                }
            },
            {
                id: titleId,
                type: 'text',
                parentId: sectionId,
                content: 'Powerful Features',
                styles: { fontSize: '42px', fontWeight: 'bold', color: 'white' }
            },
            {
                id: gridId,
                type: 'container',
                parentId: sectionId,
                children: [],
                styles: {
                    display: 'grid',
                    gridTemplateColumns: 'repeat(3, 1fr)',
                    gap: '32px',
                    width: '100%',
                    maxWidth: '1200px'
                }
            }
        ];

        const features = ['Performance', 'Scalability', 'Security'];
        features.forEach((feat, i) => {
            const cardId = uuidv4();
            const featTitleId = uuidv4();
            elements[elements.length - 1].children!.push(cardId);
            elements.push(
                {
                    id: cardId,
                    type: 'container',
                    parentId: gridId,
                    children: [featTitleId],
                    styles: {
                        padding: '32px',
                        backgroundColor: '#1A1A1A',
                        borderRadius: '16px',
                        border: '1px solid #333'
                    }
                },
                {
                    id: featTitleId,
                    type: 'text',
                    parentId: cardId,
                    content: feat,
                    styles: { fontSize: '20px', fontWeight: 'bold', color: 'var(--accent-primary)' }
                }
            );
        });

        return elements;
    }

    private static getDefaultTemplate(prompt: string): DesignerElement[] {
        const sectionId = uuidv4();
        const textId = uuidv4();
        return [
            {
                id: sectionId,
                type: 'section',
                name: 'Fallback Section',
                parentId: null,
                children: [textId],
                styles: { padding: '100px', display: 'flex', justifyContent: 'center' }
            },
            {
                id: textId,
                type: 'text',
                parentId: sectionId,
                content: `(Mock Mode) Generated: ${prompt}`,
                styles: { fontSize: '24px', color: 'white' }
            }
        ];
    }
}
