import { ProjectState } from "@/types/designer";
import { SourceCompiler } from "./SourceCompiler";
import { PageCompiler } from "./PageCompiler";
import { ASTCompiler } from "./ASTCompiler";
import JSZip from "jszip";

/**
 * ProjectScaffolder generates the full file structure for a Next.js project.
 */
export class ProjectScaffolder {
  /**
   * Generates all files and triggers a ZIP download.
   */
  static async downloadProjectZip(project: ProjectState): Promise<void> {
    const files = await this.scaffold(project);
    const zip = new JSZip();

    Object.entries(files).forEach(([path, content]) => {
      zip.file(path, content);
    });

    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${project.name.toLowerCase().replace(/\s+/g, '-')}-export.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  /**
   * Generates all files for the project.
   */
  static async scaffold(project: ProjectState): Promise<Record<string, string>> {
    let files: Record<string, string> = {};

    // 1. Pages and Components
    // Batch 4.5.1: Use AST Compiler for robust Pages
    const pages = await ASTCompiler.compilePages(project);
    files = { ...files, ...pages };

    // Batch 4.5.1: Use AST Compiler for robust Master Components
    const components = await ASTCompiler.compileMasterComponents(project);
    files = { ...files, ...components };

    // 2. Config Files
    files['package.json'] = this.generatePackageJson(project);
    files['tailwind.config.ts'] = this.generateTailwindConfig();
    files['next.config.js'] = this.generateNextConfig();
    files['app/layout.tsx'] = this.generateRootLayout(project);
    files['app/globals.css'] = this.generateGlobalsCss(project);

    // 3. Serverless Functions (Phase 10.1)
    Object.values(project.serverlessFunctions || {}).forEach(fn => {
      // Convert route like '/api/hello' to 'app/api/hello/route.ts'
      const relativePath = fn.route.startsWith('/') ? fn.route.substring(1) : fn.route;
      const filePath = `app/${relativePath}/route.ts`;
      files[filePath] = fn.code;
    });

    files['lib/runtime/LogicEngine.ts'] = this.generateLogicEngineRuntime();
    files['lib/runtime/useLogicEngine.ts'] = this.generateLogicEngineHook();

    return files;
  }

  private static generatePackageJson(project: ProjectState): string {
    return JSON.stringify({
      name: project.name.toLowerCase().replace(/\s+/g, '-'),
      version: "0.1.0",
      private: true,
      scripts: {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint"
      },
      dependencies: {
        "next": "^14.0.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "framer-motion": "^11.0.0",
        "lucide-react": "^0.300.0",
        "pglite": "^0.1.0",
        "clsx": "^2.0.0",
        "tailwind-merge": "^2.0.0"
      },
      devDependencies: {
        "typescript": "^5.0.0",
        "@types/node": "^20.0.0",
        "@types/react": "^18.2.0",
        "@types/react-dom": "^18.2.0",
        "postcss": "^8.0.0",
        "tailwindcss": "^3.4.0",
        "autoprefixer": "^10.0.0"
      }
    }, null, 2);
  }

  private static generateTailwindConfig(): string {
    return `
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
`.trim();
  }

  private static generateNextConfig(): string {
    return `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}
module.exports = nextConfig
`.trim();
  }

  private static generateRootLayout(project: ProjectState): string {
    return `
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "${project.name}",
  description: "Generated by OMNIOS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`.trim();
  }

  private static generateGlobalsCss(project: ProjectState): string {
    return `
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`.trim();
  }

  private static generateLogicEngineRuntime(): string {
    return `
export class LogicEngine {
  private blueprints: any;
  constructor(blueprints: any) { this.blueprints = blueprints; }
  executeBlueprint(id: string, payload?: any) {
    console.log("Executing Blueprint:", id, payload);
    // Real logic interpretation would go here
  }
}
`.trim();
  }

  private static generateLogicEngineHook(): string {
    return `
import { useMemo } from 'react';
import { LogicEngine } from './LogicEngine';

export const useLogicEngine = () => {
    const engine = useMemo(() => new LogicEngine({}), []);
    return {
        executeBlueprint: (id: string, payload?: any) => engine.executeBlueprint(id, payload)
    };
};
`.trim();
  }

  /**
   * Domain Management (Phase 5.4)
   */
  static async addDomainToVercel(projectId: string, domain: string, token: string): Promise<boolean> {
    const res = await fetch(`https://api.vercel.com/v9/projects/${projectId}/domains`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: domain })
    });
    return res.ok;
  }
}
