
import { ProjectState } from "@/types/designer";
import JSZip from 'jszip';

export class ProjectExporter {
    /**
     * Generates a Dockerfile for the OMNIOS project.
     * Assumes a Next.js or generic Node.js structure.
     */
    public static generateDockerfile(project: ProjectState): string {
        return `
# Auto-generated Dockerfile by OMNIOS
FROM node:18-alpine AS base

# Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Environment variables
ENV NEXT_TELEMETRY_DISABLED 1

# Build application
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
`.trim();
    }

    /**
     * Prepares a deployable ZIP bundle of the project.
     * This simulates the "Build" step.
     */
    public static async prepareBuildBundle(project: ProjectState): Promise<Blob> {
        const zip = new JSZip();

        // 1. Add Configuration
        zip.file("package.json", JSON.stringify({
            name: (project.name || "omnios-project").toLowerCase().replace(/\s+/g, '-'),
            version: "0.1.0",
            scripts: {
                "dev": "next dev",
                "build": "next build",
                "start": "next start"
            },
            dependencies: {
                "next": "14.1.0",
                "react": "^18",
                "react-dom": "^18"
            }
        }, null, 2));

        // 2. Add Dockerfile
        zip.file("Dockerfile", this.generateDockerfile(project));

        // 3. Add Source Code (Simulated)
        // In a real scenario, this would traverse the component tree and generate React code
        const pagesFolder = zip.folder("pages");

        // Index Page
        pagesFolder?.file("index.tsx", `
import React from 'react';
export default function Home() {
    return (
        <div style={{ fontFamily: 'sans-serif', padding: 40 }}>
            <h1>${project.name}</h1>
            <p>Generated by OMNIOS</p>
            {/* Render elements here */}
        </div>
    );
}
        `.trim());

        // 4. Generate Blob
        return await zip.generateAsync({ type: "blob" });
    }
}
